"""add company_puc_config and company_rate_overrides

Revision ID: 515fdf0e01b9
Revises: b8c9d0e1f2a3
Create Date: 2026-05-31 11:51:01.349784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "515fdf0e01b9"
down_revision: Union[str, Sequence[str], None] = "b8c9d0e1f2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_puc_config",
        sa.Column("company_nit", sa.String(length=20), nullable=False),
        sa.Column("cuenta_codigo", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("custom_nombre", sa.String(length=255), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_nit"], ["company_settings.nit"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["cuenta_codigo"],
            ["cuentas_puc.codigo"],
        ),
        sa.PrimaryKeyConstraint("company_nit", "cuenta_codigo"),
    )
    op.create_index(
        op.f("ix_company_puc_config_company_nit"),
        "company_puc_config",
        ["company_nit"],
        unique=False,
    )
    op.create_table(
        "company_rate_overrides",
        sa.Column("company_nit", sa.String(length=20), nullable=False),
        sa.Column("rate_code", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("norma_referencia", sa.String(length=128), nullable=True),
        sa.Column("vigente_desde", sa.Date(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_nit"], ["company_settings.nit"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("company_nit", "rate_code"),
    )
    op.create_index(
        op.f("ix_company_rate_overrides_company_nit"),
        "company_rate_overrides",
        ["company_nit"],
        unique=False,
    )
    op.alter_column(
        "ajustes_fiscales",
        "id",
        existing_type=sa.UUID(),
        type_=sa.String(length=36),
        comment="UUID generated by Postgres gen_random_uuid()",
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.alter_column(
        "ajustes_fiscales",
        "seccion",
        existing_type=sa.VARCHAR(length=32),
        comment="ESF_ACTIVO | ESF_PASIVO | ESF_PATRIMONIO | ERI_INGRESO | ERI_COSTO | ERI_GASTO",
        existing_nullable=False,
    )
    op.alter_column(
        "ajustes_fiscales",
        "tipo_diferencia",
        existing_type=sa.VARCHAR(length=32),
        comment="permanente | temporaria_imponible | temporaria_deducible",
        existing_nullable=False,
    )
    op.alter_column(
        "ajustes_fiscales",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ajustes_fiscales",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_ajustes_fiscales_nit_year"), table_name="ajustes_fiscales")
    op.drop_index(op.f("ix_ajustes_fiscales_seccion"), table_name="ajustes_fiscales")
    op.create_index(
        op.f("ix_ajustes_fiscales_company_nit"),
        "ajustes_fiscales",
        ["company_nit"],
        unique=False,
    )
    op.alter_column(
        "audit_logs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment="Owning company NIT (tenant)",
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "created_by",
        existing_type=sa.TEXT(),
        comment="UUID of the authenticated user who triggered the action",
        existing_nullable=True,
    )
    op.alter_column(
        "company_settings",
        "tasa_renta",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment="Tarifa impuesto de renta societario — Art. 240 ET, 35% (Ley 2277/2022).",
        existing_comment="Tarifa impuesto de renta societario - Art. 240 ET, 35% (Ley 2277/2022).",
        existing_nullable=False,
        existing_server_default=sa.text("0.350000"),
    )
    op.alter_column(
        "company_settings",
        "locked_pathway",
        existing_type=sa.VARCHAR(length=30),
        comment="'build_from_scratch' (Vía A) or 'work_with_existing' (Vía B) — set on first upload, immutable after",
        existing_comment="'build_from_scratch' (Vía A) or 'work_with_existing' (Vía B) — set on first upload",
        existing_nullable=True,
    )
    op.alter_column(
        "financial_statements",
        "frequency",
        existing_type=sa.VARCHAR(length=20),
        comment="monthly | quarterly | annual | custom — extracted by LLM or inferred from period span. Annual gates the NIC 7 derivation.",
        existing_comment="monthly | quarterly | annual | custom — extracted by LLM or inferred from period span",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_financial_statements_entity_nit"), table_name="financial_statements"
    )
    op.drop_index(
        op.f("ix_financial_statements_entity_type_period"),
        table_name="financial_statements",
    )
    op.alter_column(
        "ingest_jobs",
        "classification_confidence",
        existing_type=sa.NUMERIC(precision=4, scale=3),
        comment="Classifier confidence 0-1 when available",
        existing_nullable=True,
    )
    op.alter_column(
        "ingest_jobs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment="Tenant NIT supplied by the caller at upload time",
        existing_nullable=True,
    )
    op.alter_column(
        "national_rates",
        "code",
        existing_type=sa.VARCHAR(length=64),
        comment="Stable identifier, e.g. 'retefuente_servicios'",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "value",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment="Rate as decimal fraction, e.g. 0.04 for 4%",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "norma_referencia",
        existing_type=sa.VARCHAR(length=128),
        comment="Legal citation, e.g. 'Art. 392 ET'",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "vigente_desde",
        existing_type=sa.DATE(),
        comment="Effective date of this rate",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment="Owning company NIT (tenant)",
        existing_nullable=False,
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "year",
        existing_type=sa.INTEGER(),
        comment="Year the loss was incurred",
        existing_nullable=False,
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "monto_perdida",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        comment="Total fiscal loss for the year",
        existing_nullable=False,
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "monto_compensado",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        comment="Amount already compensated in subsequent years",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "monto_pendiente",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        comment="Pending amount = monto_perdida - monto_compensado (maintained by app)",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "decreto",
        existing_type=sa.VARCHAR(length=100),
        comment="Regulatory reference, e.g. 'Art. 147 ET'",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_perdidas_company"), table_name="perdidas_fiscales_acumuladas"
    )
    op.drop_constraint(
        op.f("perdidas_fiscales_acumuladas_company_nit_year_key"),
        "perdidas_fiscales_acumuladas",
        type_="unique",
    )
    op.create_index(
        op.f("ix_perdidas_fiscales_acumuladas_company_nit"),
        "perdidas_fiscales_acumuladas",
        ["company_nit"],
        unique=False,
    )
    op.alter_column(
        "reteica_tarifas",
        "municipio",
        existing_type=sa.VARCHAR(length=100),
        comment="Lowercase normalized city name, e.g. 'bogota', 'cali'",
        existing_comment="Lowercase normalized city name",
        existing_nullable=False,
    )
    op.alter_column(
        "reteica_tarifas",
        "ciiu_seccion",
        existing_type=sa.VARCHAR(length=10),
        comment="CIIU section letter (A-U) or 'general' for city default",
        existing_comment="CIIU section letter (A-U) or 'general'",
        existing_nullable=False,
    )
    op.alter_column(
        "reteica_tarifas",
        "fuente",
        existing_type=sa.VARCHAR(length=255),
        comment="Legal source, e.g. 'Acuerdo 065 Bogotá 2016'",
        existing_nullable=True,
    )
    op.alter_column(
        "reteica_tarifas",
        "base_minima_uvt",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment="Municipal ReteICA base mínima in UVT units. Bogotá=4, Medellín=15, Cali=3. Default 4 UVT (Bogotá reference). Decreto 572 does NOT apply to ReteICA — each municipio sets its own base.",
        existing_comment="Municipal ReteICA base mínima in UVT units. Bogotá=4, Medellín=15, Cali=3. Default 4 UVT (Bogotá reference). Decreto 572 does NOT apply to ReteICA — each municipio sets own base.",
        existing_nullable=True,
        existing_server_default=sa.text("'4'::numeric"),
    )
    op.alter_column(
        "tarifas_renta",
        "actividad",
        existing_type=sa.VARCHAR(length=32),
        comment="general | financiero | hidroelectrico | otro — NULL means any actividad",
        existing_comment="general | financiero | hidroelectrico | otro — NULL means any",
        existing_nullable=True,
    )
    op.alter_column(
        "tarifas_renta",
        "sobretasa",
        existing_type=sa.NUMERIC(precision=5, scale=4),
        comment="Surcharge decimal fraction, e.g. 0.0500 for financial sector",
        existing_comment="Surcharge decimal fraction, e.g. 0.0500",
        existing_nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "tax_base_minima",
        "concepto",
        existing_type=sa.VARCHAR(length=64),
        comment="One of: retefuente_servicios, retefuente_bienes, retefuente_arrendamiento, reteica",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_base_minima",
        "uvt_units",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment="Threshold in UVT units, e.g. 4.00 for 4 UVT",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_base_minima",
        "year",
        existing_type=sa.INTEGER(),
        comment="Fiscal year",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_base_minima",
        "effective_from",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        comment="Start of validity period",
        existing_nullable=True,
    )
    op.alter_column(
        "tax_base_minima",
        "effective_to",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        comment="End of validity period",
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("tax_base_minima_concepto_year_key"), "tax_base_minima", type_="unique"
    )
    op.create_index(
        op.f("ix_tax_base_minima_concepto"),
        "tax_base_minima",
        ["concepto"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tax_base_minima_year"), "tax_base_minima", ["year"], unique=False
    )
    op.alter_column(
        "tax_concepts",
        "code",
        existing_type=sa.VARCHAR(length=16),
        comment="Stable identifier, e.g. 'compras_pj', 'pes_servicios_digitales'",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_concepts",
        "renglon_350",
        existing_type=sa.VARCHAR(length=8),
        comment="F350 renglón number (DIAN form 350)",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_concepts",
        "aplica_a",
        existing_type=sa.VARCHAR(length=4),
        comment="PJ = persona jurídica | PN = persona natural | AMB = ambos",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_concepts",
        "tarifa_default",
        existing_type=sa.NUMERIC(precision=6, scale=4),
        comment="Default retention rate as decimal fraction, e.g. 0.0250",
        existing_nullable=True,
    )
    op.alter_column(
        "tax_concepts",
        "base_minima_uvt",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment="Threshold in UVT below which retention does not apply",
        existing_nullable=True,
    )
    op.alter_column(
        "tax_concepts",
        "categoria",
        existing_type=sa.VARCHAR(length=32),
        comment="compras | servicios | honorarios | arrendamiento | hidrocarburos | minerales | pes | salarios | ica | iva | otros",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_concepts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tax_concepts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_tax_concepts_categoria"), table_name="tax_concepts")
    op.drop_index(op.f("ix_tax_concepts_renglon_350"), table_name="tax_concepts")
    op.alter_column(
        "tax_declaration_drafts",
        "dian_acknowledgment",
        existing_type=sa.VARCHAR(length=64),
        comment="Número de radicado MUISCA — set when status=filed",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("uq_transactions_posted_pending_id"), table_name="transactions_posted"
    )
    op.drop_index(op.f("idx_user_company_company_nit"), table_name="user_company")
    op.drop_index(op.f("idx_user_company_user_id"), table_name="user_company")
    op.alter_column(
        "uvt_values",
        "year",
        existing_type=sa.INTEGER(),
        comment="Fiscal year, e.g. 2026",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "uvt_values",
        "value",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        comment="UVT value in COP pesos, e.g. 52374.00",
        existing_nullable=False,
    )
    op.alter_column(
        "uvt_values",
        "referencia_normativa",
        existing_type=sa.VARCHAR(length=64),
        comment="DIAN regulatory reference that published this UVT, e.g. 'Resolución 000238 de 2025'",
        existing_nullable=True,
    )
    op.alter_column(
        "uvt_values",
        "effective_from",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        comment="Start of validity period",
        existing_nullable=True,
    )
    op.alter_column(
        "uvt_values",
        "effective_to",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        comment="End of validity period",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "uvt_values",
        "effective_to",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        comment=None,
        existing_comment="End of validity period",
        existing_nullable=True,
    )
    op.alter_column(
        "uvt_values",
        "effective_from",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        comment=None,
        existing_comment="Start of validity period",
        existing_nullable=True,
    )
    op.alter_column(
        "uvt_values",
        "referencia_normativa",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="DIAN regulatory reference that published this UVT, e.g. 'Resolución 000238 de 2025'",
        existing_nullable=True,
    )
    op.alter_column(
        "uvt_values",
        "value",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        comment=None,
        existing_comment="UVT value in COP pesos, e.g. 52374.00",
        existing_nullable=False,
    )
    op.alter_column(
        "uvt_values",
        "year",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Fiscal year, e.g. 2026",
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(
        op.f("idx_user_company_user_id"), "user_company", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_user_company_company_nit"),
        "user_company",
        ["company_nit"],
        unique=False,
    )
    op.create_index(
        op.f("uq_transactions_posted_pending_id"),
        "transactions_posted",
        ["transaction_pending_id"],
        unique=True,
    )
    op.alter_column(
        "tax_declaration_drafts",
        "dian_acknowledgment",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Número de radicado MUISCA — set when status=filed",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_tax_concepts_renglon_350"),
        "tax_concepts",
        ["renglon_350"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tax_concepts_categoria"), "tax_concepts", ["categoria"], unique=False
    )
    op.alter_column(
        "tax_concepts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tax_concepts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tax_concepts",
        "categoria",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="compras | servicios | honorarios | arrendamiento | hidrocarburos | minerales | pes | salarios | ica | iva | otros",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_concepts",
        "base_minima_uvt",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment=None,
        existing_comment="Threshold in UVT below which retention does not apply",
        existing_nullable=True,
    )
    op.alter_column(
        "tax_concepts",
        "tarifa_default",
        existing_type=sa.NUMERIC(precision=6, scale=4),
        comment=None,
        existing_comment="Default retention rate as decimal fraction, e.g. 0.0250",
        existing_nullable=True,
    )
    op.alter_column(
        "tax_concepts",
        "aplica_a",
        existing_type=sa.VARCHAR(length=4),
        comment=None,
        existing_comment="PJ = persona jurídica | PN = persona natural | AMB = ambos",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_concepts",
        "renglon_350",
        existing_type=sa.VARCHAR(length=8),
        comment=None,
        existing_comment="F350 renglón number (DIAN form 350)",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_concepts",
        "code",
        existing_type=sa.VARCHAR(length=16),
        comment=None,
        existing_comment="Stable identifier, e.g. 'compras_pj', 'pes_servicios_digitales'",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_tax_base_minima_year"), table_name="tax_base_minima")
    op.drop_index(op.f("ix_tax_base_minima_concepto"), table_name="tax_base_minima")
    op.create_unique_constraint(
        op.f("tax_base_minima_concepto_year_key"),
        "tax_base_minima",
        ["concepto", "year"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "tax_base_minima",
        "effective_to",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        comment=None,
        existing_comment="End of validity period",
        existing_nullable=True,
    )
    op.alter_column(
        "tax_base_minima",
        "effective_from",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        comment=None,
        existing_comment="Start of validity period",
        existing_nullable=True,
    )
    op.alter_column(
        "tax_base_minima",
        "year",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Fiscal year",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_base_minima",
        "uvt_units",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment=None,
        existing_comment="Threshold in UVT units, e.g. 4.00 for 4 UVT",
        existing_nullable=False,
    )
    op.alter_column(
        "tax_base_minima",
        "concepto",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="One of: retefuente_servicios, retefuente_bienes, retefuente_arrendamiento, reteica",
        existing_nullable=False,
    )
    op.alter_column(
        "tarifas_renta",
        "sobretasa",
        existing_type=sa.NUMERIC(precision=5, scale=4),
        comment="Surcharge decimal fraction, e.g. 0.0500",
        existing_comment="Surcharge decimal fraction, e.g. 0.0500 for financial sector",
        existing_nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "tarifas_renta",
        "actividad",
        existing_type=sa.VARCHAR(length=32),
        comment="general | financiero | hidroelectrico | otro — NULL means any",
        existing_comment="general | financiero | hidroelectrico | otro — NULL means any actividad",
        existing_nullable=True,
    )
    op.alter_column(
        "reteica_tarifas",
        "base_minima_uvt",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment="Municipal ReteICA base mínima in UVT units. Bogotá=4, Medellín=15, Cali=3. Default 4 UVT (Bogotá reference). Decreto 572 does NOT apply to ReteICA — each municipio sets own base.",
        existing_comment="Municipal ReteICA base mínima in UVT units. Bogotá=4, Medellín=15, Cali=3. Default 4 UVT (Bogotá reference). Decreto 572 does NOT apply to ReteICA — each municipio sets its own base.",
        existing_nullable=True,
        existing_server_default=sa.text("'4'::numeric"),
    )
    op.alter_column(
        "reteica_tarifas",
        "fuente",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Legal source, e.g. 'Acuerdo 065 Bogotá 2016'",
        existing_nullable=True,
    )
    op.alter_column(
        "reteica_tarifas",
        "ciiu_seccion",
        existing_type=sa.VARCHAR(length=10),
        comment="CIIU section letter (A-U) or 'general'",
        existing_comment="CIIU section letter (A-U) or 'general' for city default",
        existing_nullable=False,
    )
    op.alter_column(
        "reteica_tarifas",
        "municipio",
        existing_type=sa.VARCHAR(length=100),
        comment="Lowercase normalized city name",
        existing_comment="Lowercase normalized city name, e.g. 'bogota', 'cali'",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_perdidas_fiscales_acumuladas_company_nit"),
        table_name="perdidas_fiscales_acumuladas",
    )
    op.create_unique_constraint(
        op.f("perdidas_fiscales_acumuladas_company_nit_year_key"),
        "perdidas_fiscales_acumuladas",
        ["company_nit", "year"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_perdidas_company"),
        "perdidas_fiscales_acumuladas",
        ["company_nit"],
        unique=False,
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "decreto",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Regulatory reference, e.g. 'Art. 147 ET'",
        existing_nullable=True,
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "monto_pendiente",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        comment=None,
        existing_comment="Pending amount = monto_perdida - monto_compensado (maintained by app)",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "monto_compensado",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        comment=None,
        existing_comment="Amount already compensated in subsequent years",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "monto_perdida",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        comment=None,
        existing_comment="Total fiscal loss for the year",
        existing_nullable=False,
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "year",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Year the loss was incurred",
        existing_nullable=False,
    )
    op.alter_column(
        "perdidas_fiscales_acumuladas",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Owning company NIT (tenant)",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "national_rates",
        "vigente_desde",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="Effective date of this rate",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "norma_referencia",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="Legal citation, e.g. 'Art. 392 ET'",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "value",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment=None,
        existing_comment="Rate as decimal fraction, e.g. 0.04 for 4%",
        existing_nullable=False,
    )
    op.alter_column(
        "national_rates",
        "code",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Stable identifier, e.g. 'retefuente_servicios'",
        existing_nullable=False,
    )
    op.alter_column(
        "ingest_jobs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Tenant NIT supplied by the caller at upload time",
        existing_nullable=True,
    )
    op.alter_column(
        "ingest_jobs",
        "classification_confidence",
        existing_type=sa.NUMERIC(precision=4, scale=3),
        comment=None,
        existing_comment="Classifier confidence 0-1 when available",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_financial_statements_entity_type_period"),
        "financial_statements",
        ["entity_nit", "statement_type", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_statements_entity_nit"),
        "financial_statements",
        ["entity_nit"],
        unique=False,
    )
    op.alter_column(
        "financial_statements",
        "frequency",
        existing_type=sa.VARCHAR(length=20),
        comment="monthly | quarterly | annual | custom — extracted by LLM or inferred from period span",
        existing_comment="monthly | quarterly | annual | custom — extracted by LLM or inferred from period span. Annual gates the NIC 7 derivation.",
        existing_nullable=True,
    )
    op.alter_column(
        "company_settings",
        "locked_pathway",
        existing_type=sa.VARCHAR(length=30),
        comment="'build_from_scratch' (Vía A) or 'work_with_existing' (Vía B) — set on first upload",
        existing_comment="'build_from_scratch' (Vía A) or 'work_with_existing' (Vía B) — set on first upload, immutable after",
        existing_nullable=True,
    )
    op.alter_column(
        "company_settings",
        "tasa_renta",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment="Tarifa impuesto de renta societario - Art. 240 ET, 35% (Ley 2277/2022).",
        existing_comment="Tarifa impuesto de renta societario — Art. 240 ET, 35% (Ley 2277/2022).",
        existing_nullable=False,
        existing_server_default=sa.text("0.350000"),
    )
    op.alter_column(
        "audit_logs",
        "created_by",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="UUID of the authenticated user who triggered the action",
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Owning company NIT (tenant)",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_ajustes_fiscales_company_nit"), table_name="ajustes_fiscales"
    )
    op.create_index(
        op.f("ix_ajustes_fiscales_seccion"),
        "ajustes_fiscales",
        ["seccion"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ajustes_fiscales_nit_year"),
        "ajustes_fiscales",
        ["company_nit", "year"],
        unique=False,
    )
    op.alter_column(
        "ajustes_fiscales",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ajustes_fiscales",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ajustes_fiscales",
        "tipo_diferencia",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="permanente | temporaria_imponible | temporaria_deducible",
        existing_nullable=False,
    )
    op.alter_column(
        "ajustes_fiscales",
        "seccion",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="ESF_ACTIVO | ESF_PASIVO | ESF_PATRIMONIO | ERI_INGRESO | ERI_COSTO | ERI_GASTO",
        existing_nullable=False,
    )
    op.alter_column(
        "ajustes_fiscales",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.UUID(),
        comment=None,
        existing_comment="UUID generated by Postgres gen_random_uuid()",
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.drop_index(
        op.f("ix_company_rate_overrides_company_nit"),
        table_name="company_rate_overrides",
    )
    op.drop_table("company_rate_overrides")
    op.drop_index(
        op.f("ix_company_puc_config_company_nit"), table_name="company_puc_config"
    )
    op.drop_table("company_puc_config")
    # ### end Alembic commands ###
