"""add_es_declarante_and_tax_declaration_drafts

Revision ID: 85397898945d
Revises: 5bc6243a55b2
Create Date: 2026-04-22 20:37:28.253080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85397898945d"
down_revision: Union[str, Sequence[str], None] = "5bc6243a55b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_declaration_drafts",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("company_nit", sa.String(length=20), nullable=False),
        sa.Column(
            "form_type",
            sa.String(length=10),
            nullable=False,
            comment="F300 | F350 | F110 | ICA | F220",
        ),
        sa.Column(
            "period_start",
            sa.String(length=10),
            nullable=False,
            comment="ISO date YYYY-MM-DD",
        ),
        sa.Column(
            "period_end",
            sa.String(length=10),
            nullable=False,
            comment="ISO date YYYY-MM-DD",
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="draft | reviewed | filed",
        ),
        sa.Column(
            "fields_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
            comment="List of {renglon, label, value, source, confidence, requires_review}",
        ),
        sa.Column(
            "warnings_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
            comment="List of {field, message} for fields that need accountant review",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_nit"], ["company_settings.nit"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tax_declaration_drafts_company_nit"),
        "tax_declaration_drafts",
        ["company_nit"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tax_declaration_drafts_id"),
        "tax_declaration_drafts",
        ["id"],
        unique=False,
    )
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.drop_index(op.f("ix_chat_sessions_created_at"), table_name="chat_sessions")
    op.create_index(op.f("ix_chat_sessions_id"), "chat_sessions", ["id"], unique=False)
    op.add_column(
        "company_settings",
        sa.Column(
            "es_declarante",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
            comment="True=declarante de renta (lower retefuente rates), False=no declarante",
        ),
    )
    op.alter_column(
        "company_settings",
        "tasa_ica",
        existing_type=sa.NUMERIC(precision=10, scale=8),
        comment="Tarifa ICA sobre ingresos brutos (Ley 14/1983). Varía por municipio/CIIU.",
        existing_nullable=False,
        existing_server_default=sa.text("0.00690000"),
    )
    op.alter_column(
        "company_settings",
        "tasa_renta",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment="Tarifa impuesto de renta societario — Art. 240 ET, 35% (Ley 2277/2022).",
        existing_nullable=False,
        existing_server_default=sa.text("0.350000"),
    )
    op.alter_column(
        "financial_statements",
        "source_mode",
        existing_type=sa.VARCHAR(length=20),
        comment="direct | derived | derived_from_journal",
        existing_comment="direct | derived",
        existing_nullable=False,
        existing_server_default=sa.text("'direct'::character varying"),
    )
    op.drop_index(
        op.f("ix_financial_statements_entity_nit"), table_name="financial_statements"
    )
    op.drop_index(
        op.f("ix_financial_statements_entity_type_period"),
        table_name="financial_statements",
    )
    op.drop_index(
        op.f("ix_vector_documents_content_tsv"),
        table_name="vector_documents",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_vector_documents_embedding_hnsw"),
        table_name="vector_documents",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_column("vector_documents", "content_tsv")
    op.drop_column("vector_documents", "embedding")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vector_documents",
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "vector_documents",
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('spanish'::regconfig, content)", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_vector_documents_embedding_hnsw"),
        "vector_documents",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("ix_vector_documents_content_tsv"),
        "vector_documents",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_financial_statements_entity_type_period"),
        "financial_statements",
        ["entity_nit", "statement_type", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_statements_entity_nit"),
        "financial_statements",
        ["entity_nit"],
        unique=False,
    )
    op.alter_column(
        "financial_statements",
        "source_mode",
        existing_type=sa.VARCHAR(length=20),
        comment="direct | derived",
        existing_comment="direct | derived | derived_from_journal",
        existing_nullable=False,
        existing_server_default=sa.text("'direct'::character varying"),
    )
    op.alter_column(
        "company_settings",
        "tasa_renta",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment=None,
        existing_comment="Tarifa impuesto de renta societario — Art. 240 ET, 35% (Ley 2277/2022).",
        existing_nullable=False,
        existing_server_default=sa.text("0.350000"),
    )
    op.alter_column(
        "company_settings",
        "tasa_ica",
        existing_type=sa.NUMERIC(precision=10, scale=8),
        comment=None,
        existing_comment="Tarifa ICA sobre ingresos brutos (Ley 14/1983). Varía por municipio/CIIU.",
        existing_nullable=False,
        existing_server_default=sa.text("0.00690000"),
    )
    op.drop_column("company_settings", "es_declarante")
    op.drop_index(op.f("ix_chat_sessions_id"), table_name="chat_sessions")
    op.create_index(
        op.f("ix_chat_sessions_created_at"),
        "chat_sessions",
        ["created_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.create_index(
        op.f("ix_chat_messages_created_at"),
        "chat_messages",
        ["created_at"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_tax_declaration_drafts_id"), table_name="tax_declaration_drafts"
    )
    op.drop_index(
        op.f("ix_tax_declaration_drafts_company_nit"),
        table_name="tax_declaration_drafts",
    )
    op.drop_table("tax_declaration_drafts")
    # ### end Alembic commands ###
