"""add document_type and pathway to ingest_jobs

Revision ID: b232aff042b8
Revises: d4e5f6a7b8c9
Create Date: 2026-03-21 12:29:51.376097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b232aff042b8'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ingest_id', sa.String(length=50), nullable=False),
    sa.Column('statement_type', sa.String(length=50), nullable=False, comment='balance_general | estado_resultados | libro_auxiliar'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entity_nit', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Full parsed financial statement data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingest_id'], ['ingest_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_id'), 'financial_statements', ['id'], unique=False)
    op.create_index(op.f('ix_financial_statements_ingest_id'), 'financial_statements', ['ingest_id'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='e.g. transaction_created, agent_ran',
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='e.g. transaction, job, ingest',
               existing_nullable=True)
    op.drop_constraint(op.f('cuentas_puc_codigo_key'), 'cuentas_puc', type_='unique')
    op.drop_index(op.f('ix_cuentas_puc_codigo'), table_name='cuentas_puc')
    op.create_index(op.f('ix_cuentas_puc_codigo'), 'cuentas_puc', ['codigo'], unique=True)
    op.add_column('ingest_jobs', sa.Column('document_type', sa.String(length=50), nullable=True, comment='DocumentType enum value'))
    op.add_column('ingest_jobs', sa.Column('pathway', sa.String(length=30), nullable=True, comment='build_from_scratch | work_with_existing'))
    op.alter_column('ingest_jobs', 'raw_preview',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Quick preview of extracted data',
               existing_nullable=True)
    op.alter_column('ingest_jobs', 'extraction_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of error messages',
               existing_nullable=True)
    op.alter_column('journal_entry_lines', 'comprobante',
               existing_type=sa.VARCHAR(length=20),
               comment='Voucher/receipt number',
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entry_lines_posted_id'), table_name='journal_entry_lines')
    op.create_index(op.f('ix_journal_entry_lines_transaction_posted_id'), 'journal_entry_lines', ['transaction_posted_id'], unique=False)
    op.alter_column('process_jobs', 'progress',
               existing_type=sa.INTEGER(),
               comment='0-100 percent',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('process_jobs', 'agent_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Timeline of agent steps',
               existing_nullable=True)
    op.drop_constraint(op.f('terceros_nit_key'), 'terceros', type_='unique')
    op.drop_index(op.f('ix_terceros_nit'), table_name='terceros')
    op.create_index(op.f('ix_terceros_nit'), 'terceros', ['nit'], unique=True)
    op.alter_column('transactions_pending', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Line items from document',
               existing_nullable=True)
    op.alter_column('transactions_pending', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full Gemini extraction result',
               existing_nullable=True)
    op.alter_column('transactions_posted', 'tax_references',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Legal references: Art. 383 ET, etc.',
               existing_nullable=True)
    op.alter_column('transactions_posted', 'agent_reasoning',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Agent decision log per step',
               existing_nullable=True)
    op.drop_index(op.f('ix_transactions_posted_pending_id'), table_name='transactions_posted')
    op.create_index(op.f('ix_transactions_posted_transaction_pending_id'), 'transactions_posted', ['transaction_pending_id'], unique=False)
    op.alter_column('vector_documents', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_vector_documents_collection'), table_name='vector_documents')
    op.drop_index(op.f('ix_vector_documents_content_tsv'), table_name='vector_documents', postgresql_using='gin')
    op.drop_index(op.f('ix_vector_documents_embedding_hnsw'), table_name='vector_documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('vector_documents', 'content_tsv')
    op.drop_column('vector_documents', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_documents', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('vector_documents', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish'::regconfig, content)", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_vector_documents_embedding_hnsw'), 'vector_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_vector_documents_content_tsv'), 'vector_documents', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_vector_documents_collection'), 'vector_documents', ['collection_name'], unique=False)
    op.alter_column('vector_documents', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_posted_transaction_pending_id'), table_name='transactions_posted')
    op.create_index(op.f('ix_transactions_posted_pending_id'), 'transactions_posted', ['transaction_pending_id'], unique=False)
    op.alter_column('transactions_posted', 'agent_reasoning',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Agent decision log per step',
               existing_nullable=True)
    op.alter_column('transactions_posted', 'tax_references',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Legal references: Art. 383 ET, etc.',
               existing_nullable=True)
    op.alter_column('transactions_pending', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full Gemini extraction result',
               existing_nullable=True)
    op.alter_column('transactions_pending', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Line items from document',
               existing_nullable=True)
    op.drop_index(op.f('ix_terceros_nit'), table_name='terceros')
    op.create_index(op.f('ix_terceros_nit'), 'terceros', ['nit'], unique=False)
    op.create_unique_constraint(op.f('terceros_nit_key'), 'terceros', ['nit'], postgresql_nulls_not_distinct=False)
    op.alter_column('process_jobs', 'agent_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Timeline of agent steps',
               existing_nullable=True)
    op.alter_column('process_jobs', 'progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0-100 percent',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_journal_entry_lines_transaction_posted_id'), table_name='journal_entry_lines')
    op.create_index(op.f('ix_journal_entry_lines_posted_id'), 'journal_entry_lines', ['transaction_posted_id'], unique=False)
    op.alter_column('journal_entry_lines', 'comprobante',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Voucher/receipt number',
               existing_nullable=True)
    op.alter_column('ingest_jobs', 'extraction_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of error messages',
               existing_nullable=True)
    op.alter_column('ingest_jobs', 'raw_preview',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Quick preview of extracted data',
               existing_nullable=True)
    op.drop_column('ingest_jobs', 'pathway')
    op.drop_column('ingest_jobs', 'document_type')
    op.drop_index(op.f('ix_cuentas_puc_codigo'), table_name='cuentas_puc')
    op.create_index(op.f('ix_cuentas_puc_codigo'), 'cuentas_puc', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('cuentas_puc_codigo_key'), 'cuentas_puc', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='e.g. transaction, job, ingest',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='e.g. transaction_created, agent_ran',
               existing_nullable=False)
    op.drop_index(op.f('ix_financial_statements_ingest_id'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    # ### end Alembic commands ###
