"""add_user_company

Revision ID: fb08f11836cb
Revises: 33c6ac057344
Create Date: 2026-05-09 07:48:11.124694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb08f11836cb"
down_revision: Union[str, Sequence[str], None] = "33c6ac057344"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_company",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("company_nit", sa.String(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_nit"], ["company_settings.nit"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "company_nit"),
    )
    op.create_index("idx_user_company_user_id", "user_company", ["user_id"])
    op.create_index("idx_user_company_company_nit", "user_company", ["company_nit"])
    op.drop_index(op.f("ix_dian_municipios_departamento"), table_name="dian_municipios")
    op.drop_index(
        op.f("ix_dian_municipios_nombre_gin"),
        table_name="dian_municipios",
        postgresql_using="gin",
    )
    op.drop_table("dian_municipios")
    op.alter_column(
        "audit_logs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment="Owning company NIT (tenant)",
        existing_nullable=True,
    )
    op.alter_column(
        "company_settings",
        "tasa_renta",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment="Tarifa impuesto de renta societario — Art. 240 ET, 35% (Ley 2277/2022).",
        existing_comment="Tarifa impuesto de renta societario - Art. 240 ET, 35% (Ley 2277/2022).",
        existing_nullable=False,
        existing_server_default=sa.text("0.350000"),
    )
    op.drop_column("company_settings", "locked_pathway")
    op.alter_column(
        "ingest_jobs",
        "classification_confidence",
        existing_type=sa.NUMERIC(precision=4, scale=3),
        comment="Classifier confidence 0-1 when available",
        existing_nullable=True,
    )
    op.alter_column(
        "ingest_jobs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment="Tenant NIT supplied by the caller at upload time",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_vector_documents_collection_name"), table_name="vector_documents"
    )
    op.drop_index(
        op.f("ix_vector_documents_content_tsv_gin"),
        table_name="vector_documents",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_vector_documents_embedding_hnsw"),
        table_name="vector_documents",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.drop_column("vector_documents", "content_tsv")
    op.drop_column("vector_documents", "embedding")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_company_user_id", table_name="user_company")
    op.drop_index("idx_user_company_company_nit", table_name="user_company")
    op.drop_table("user_company")
    op.add_column(
        "vector_documents",
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "vector_documents",
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple'::regconfig, COALESCE(content, ''::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_vector_documents_embedding_hnsw"),
        "vector_documents",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("ix_vector_documents_content_tsv_gin"),
        "vector_documents",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_vector_documents_collection_name"),
        "vector_documents",
        ["collection_name"],
        unique=False,
    )
    op.alter_column(
        "ingest_jobs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Tenant NIT supplied by the caller at upload time",
        existing_nullable=True,
    )
    op.alter_column(
        "ingest_jobs",
        "classification_confidence",
        existing_type=sa.NUMERIC(precision=4, scale=3),
        comment=None,
        existing_comment="Classifier confidence 0-1 when available",
        existing_nullable=True,
    )
    op.add_column(
        "company_settings",
        sa.Column(
            "locked_pathway",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=True,
            comment="'build_from_scratch' (Vía A) or 'work_with_existing' (Vía B) — set on first upload",
        ),
    )
    op.alter_column(
        "company_settings",
        "tasa_renta",
        existing_type=sa.NUMERIC(precision=8, scale=6),
        comment="Tarifa impuesto de renta societario - Art. 240 ET, 35% (Ley 2277/2022).",
        existing_comment="Tarifa impuesto de renta societario — Art. 240 ET, 35% (Ley 2277/2022).",
        existing_nullable=False,
        existing_server_default=sa.text("0.350000"),
    )
    op.alter_column(
        "audit_logs",
        "company_nit",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Owning company NIT (tenant)",
        existing_nullable=True,
    )
    op.create_table(
        "dian_municipios",
        sa.Column("codigo", sa.VARCHAR(length=5), autoincrement=False, nullable=False),
        sa.Column(
            "nombre", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "departamento_codigo",
            sa.VARCHAR(length=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "departamento_nombre",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("codigo", name=op.f("dian_municipios_pkey")),
    )
    op.create_index(
        op.f("ix_dian_municipios_nombre_gin"),
        "dian_municipios",
        [sa.literal_column("to_tsvector('simple'::regconfig, nombre::text)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_dian_municipios_departamento"),
        "dian_municipios",
        ["departamento_codigo"],
        unique=False,
    )
    # ### end Alembic commands ###
